2024-10-04 17:52:19,371 - INFO - DragonTiger.py - 402 - Starting value: 11081.14
2024-10-04 17:52:19,371 - INFO - DragonTiger.py - 403 - Target amount: 12000
2024-10-04 17:52:19,371 - INFO - DragonTiger.py - 404 - Betted On,CurrentValue,TargetAmt,Losscount,Wincount
2024-10-04 17:52:25,842 - INFO - DragonTiger.py - 282 - D,11081.14,12000,0,0
2024-10-04 17:52:25,842 - ERROR - DragonTiger.py - 593 - An error occurred during the betting process: list index out of range
Traceback (most recent call last):
  File "c:\Users\Umesh Patel\Omnitrix\DragonTiger.py", line 572, in <module>
    if(Bethistory[len(Bethistory)-1]=='D'):
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-10-04 17:52:44,590 - INFO - DragonTiger.py - 282 - D,11081.14,12000,0,0
2024-10-04 17:52:44,590 - ERROR - DragonTiger.py - 593 - An error occurred during the betting process: list index out of range
Traceback (most recent call last):
  File "c:\Users\Umesh Patel\Omnitrix\DragonTiger.py", line 572, in <module>
    if(Bethistory[len(Bethistory)-1]=='D'):
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-10-04 17:52:50,334 - INFO - DragonTiger.py - 282 - D,11081.14,12000,0,0
2024-10-04 17:52:50,336 - ERROR - DragonTiger.py - 593 - An error occurred during the betting process: list index out of range
Traceback (most recent call last):
  File "c:\Users\Umesh Patel\Omnitrix\DragonTiger.py", line 572, in <module>
    if(Bethistory[len(Bethistory)-1]=='D'):
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-10-04 17:52:56,433 - INFO - DragonTiger.py - 282 - D,11081.14,12000,0,0
2024-10-04 17:52:56,433 - ERROR - DragonTiger.py - 593 - An error occurred during the betting process: list index out of range
Traceback (most recent call last):
  File "c:\Users\Umesh Patel\Omnitrix\DragonTiger.py", line 572, in <module>
    if(Bethistory[len(Bethistory)-1]=='D'):
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-10-04 17:55:15,580 - ERROR - DragonTiger.py - 608 - An error occurred in the main function: '>' not supported between instances of 'NoneType' and 'float'
Traceback (most recent call last):
  File "c:\Users\Umesh Patel\Omnitrix\DragonTiger.py", line 437, in <module>
    if(last_value>current_value_final):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'float'
